### ISSUE TITLE
Reduce compilation time

### ISSUE THREAD

**Issue by epage** [epage/clapng#161]
<a href="https://github.com/CreepySkeleton"><img src="https://avatars.githubusercontent.com/u/50968528?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [CreepySkeleton](https://github.com/CreepySkeleton)**
_Tuesday Jul 28, 2020 at 11:47 GMT_
_Originally opened as https://github.com/clap-rs/clap/issues/2037_

----

[All features](https://gistpreview.github.io/?8ee8a91bfe081221672908eb57fcf723)
[No features](https://gistpreview.github.io/?2e3e54008f987749cd1cbf31f8f1f0e9)

The `clap` crate (not counting dependencies) takes about 11 seconds to compile. All dependencies put together take roughly the same amount of time.

I have a few thoughts on how to improve the situation. Generally, compile time wins these days are accomplished through "compile less code", hence:
- [ ] Feature-gate `#[derive(Clone, Copy, Eq...]`. The features should probably be fine-grained, like `impl-traits-eq` enables `Eq + PartialEq`. Plus the "enable everything" `impl-traits` feature that implies all the traits.
  - [ ] Avoid using derives and use some sort of `STRUCT!` macro as shown [here](https://github.com/retep998/winapi-rs/issues/218#issuecomment-145988469). It turns out that even built-in derives have impact on compilation time when you have lots of them, and _every_ struct here has `#[derive(Debug)]`.
- [x] Optimize `proc-macro-error` (drop `syn-mid` dep). I had already done that but decided to play around a bit more and then forgot about it. Oops.
- [ ] Make clap modular so developers could choose exactly the set of features they need and avoid compile the others. I'll crate a separate issue a bit later.

The list is probably not exhaustive...

**Comment by epage** [comment]
<a href="https://github.com/mainrs"><img src="https://avatars.githubusercontent.com/u/5113257?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mainrs](https://github.com/mainrs)**
_Thursday Jul 30, 2020 at 11:31 GMT_

----

Hey!
If you want I can tackle down the trait implementation features :) How fine-grained do you want it to be though?

**Comment by epage** [comment]
<a href="https://github.com/CreepySkeleton"><img src="https://avatars.githubusercontent.com/u/50968528?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CreepySkeleton](https://github.com/CreepySkeleton)**
_Friday Jul 31, 2020 at 12:24 GMT_

----

Sure, you can try, but keep in mind that the real goal is to reduce compilation time. If the measurements will show no real difference (at least half second, everything below the threshold is noise), I will say "well we tried" and move on to other ideas.

**Comment by epage** [comment]
<a href="https://github.com/mainrs"><img src="https://avatars.githubusercontent.com/u/5113257?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mainrs](https://github.com/mainrs)**
_Friday Jul 31, 2020 at 13:35 GMT_

----

Sure thing! Could you tell me how to managed to time the compilation? And create the visuals for it as well :)

**Comment by epage** [comment]
<a href="https://github.com/CreepySkeleton"><img src="https://avatars.githubusercontent.com/u/50968528?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CreepySkeleton](https://github.com/CreepySkeleton)**
_Friday Jul 31, 2020 at 14:23 GMT_

----

The invocation was 
```sh
cargo clean # make sure the we build from scratch
cargo +nightly build -Z timings -p clap:3.0.0-beta.1 --features "yaml unstable"
```

This will create `cargo-timing-<HASH>.html` file that you can open in your web browser and see the adorable stats you were so excited about :) Then I uploaded the raw html on `gist.github.com` and linked it through `gistpreview.github.io` so you see the rendered version instead of raw HTML guts.
