### ISSUE TITLE
3.0 Release Checklist

### ISSUE THREAD

**Issue by epage** [epage/clapng#220]
<a href="https://github.com/epage"><img src="https://avatars.githubusercontent.com/u/60961?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [epage](https://github.com/epage)**
_Wednesday Oct 13, 2021 at 11:24 GMT_
_Originally opened as https://github.com/clap-rs/clap/issues/2869_

----

- [ ] 1 month of release candidate feedback
- [ ] Double check all docs
  - Match 3.0?
  - Generally, use more specific derive traits than Parser?
  - Good jumping off point for most users
  - Examples use `global_settings` where possible to raise awareness
- [ ] Double check all examples
- [ ] Double Check readme
- [ ] Double check examples on clap.rs
  - Compile?
- [ ] Changelog
- [x] Clippy Run (CI)
- [x] Rustfmt Run (CI)
- [ ] Spell Check Docs
- [ ] Blog Post

**Comment by epage** [comment]
<a href="https://github.com/wldevries"><img src="https://avatars.githubusercontent.com/u/1745610?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wldevries](https://github.com/wldevries)**
_Sunday Oct 17, 2021 at 09:48 GMT_

----

Not sure if this is the right place, but the readme in this repository for "Using Derive Macros" is incorrect at the moment. It uses `Parser` instead of the replacement type `Clap`.

**Comment by epage** [comment]
<a href="https://github.com/tranzystorek-io"><img src="https://avatars.githubusercontent.com/u/5671049?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tranzystorek-io](https://github.com/tranzystorek-io)**
_Sunday Oct 17, 2021 at 10:05 GMT_

----

@wldevries According to d840d5650e9a7085a39c620697b11d6010d4fcf7 the `Clap` trait has been renamed to `Parser` to show what it does more specifically.
